version: '3.7'

services:
  jenkins-in-docker:
    image: jenkins/jenkins:lts-slim-jdk8
    container_name: jenkins-in-docker
    restart: on-failure:3
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF-8"
      JENKINS_OPTS: ""
